ci: linting requires dist dir to exist
  Error: web/embed.go:5:12: pattern dist: no matching files found (typecheck)
  //go:embed dist
             ^
  1 issues:
  * typecheck: 1

Signed-off-by: Brady Pratt <bpratt@redhat.com>